### ISSUE TITLE
Use state logic and PID control for elevator

### ISSUE THREAD

**Issue by redPlover** [team401/2024-Robot-Code#145] opened 2024-03-04 06:31 UTC
This is an extension of #98.

**Project Scope**
- [x] Use state machine for controlling the elevator
- [x] Implement written PID controller to state logic

**Comment by jkleiber** [comment] 2024-03-18 18:34
I'm going to close this as a duplicate of #123 since I believe we have an endgame PID controller on main that works with the state machine in endgame subsystem

**Closed by jkleiber** 2024-03-18 18:34 UTC
Labels: feature, endgame
